### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zhongwen-4** [Onimaimai/nonebot-plugin-voicemusic#1]
要不你还是重构一下吧

**Comment by zhongwen-4** [comment]
这接口炸掉了，不用发了吧？
![image](https://github.com/user-attachments/assets/c234f44f-66f8-4d76-87d8-4e28acde744f)

**Comment by Onimaimai** [comment]
是下面那个
![image](https://github.com/user-attachments/assets/7371d0fe-4dca-4770-82a0-78cceb1cf071)
