### ISSUE TITLE
[Suggestion] 关于配置项及其说明的一些小建议

### ISSUE THREAD

**Issue by hanasa2023** [Onimaimai/nonebot-plugin-voicemusic#4]
- 可以登陆后通过浏览器的DevTools查看cookie，从cookie中获取qm_keyst/qqmusic_key
- 配置项中的SKEY可能具有一定的误导(?)，因为cookie中就有skey这一项，~~如果不仔细读文档的话可能会误填~~

![查看cookie](https://files.catbox.moe/hyjepy.png)

**Comment by Onimaimai** [comment]
确实
